package:
  name: nifty
  version: v1.0.7.1


source:
  path: ..


build:
  number: 0


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake

  host:
    - python
    - boost-cpp >=1.63
    - hdf5 >=1.10
    - numpy >=1.15
    - blosc
    - z5py >=2.0.5
    - vigra
    - bzip2
    - zlib
    - xtensor
    - xtensor-python
    - nlohmann_json

  run:
    - python
    - scikit-image
    - vigra
    - hdf5 >=1.10
    - numpy >=1.15
    - blosc
    - bzip2
    - zlib


test:
  imports:
    - nifty


about:
  home: https://github.com/DerThorsten/nifty
  license: MIT
  summary: Graph-based segmentation algorithms
